image: node:10.15.0
pipelines:
  default:
  - step:
      caches:
      - node
      script:
      - yarn install
      - yarn start
      services:
      - postgres
  branches:
    master:
    - step:
        deployment: production
        script:
        - pipe: atlassian/google-app-engine-deploy:0.4.0
          variables:
            KEY_FILE: $KEY_FILE
            PROJECT: $PROJECT_NAME
            DEPLOYABLES: 'app.yaml'
            SALT_ROUNDS: $SALT_ROUND
            BACKEND_URL: $BACKEND_URL
            FRONTEND_URL: $FRONTEND_URL
            MAILGUN_DOMAIN: $MAILGUN_DOMAIN
            MAILGUN_API_KEY: $MAILGUN_API_KEY
            TYPEORM_CONNECTION: 'postgres'
            TYPEORM_HOST: $TYPEORM_HOST
            TYPEORM_DATABASE: $TYPEORM_DATABASE
            TYPEORM_USERNAME: $TYPEORM_USERNAME
            TYPEORM_PASSWORD: $TYPEORM_PASSWORD
            TYPEORM_PORT: 29966
            TYPEORM_SYNCHRONIZE: "false"
            TYPEORM_LOGGING: "true"
            TYPEORM_ENTITIES: 'build/entity/*.js'
            TYPEORM_MIGRATIONS: 'build/migrations/*.js'
            TYPEORM_ENTITIES_DIR: 'build/entity'
            TYPEORM_MIGRATIONS_DIR: 'build/migrations'
            TYPEORM_DRIVER_EXTRA: '{ "ssl": true }'
    develop:
    - step:
        deployment: staging
        script:
        - pipe: atlassian/google-app-engine-deploy:0.4.0
          variables:
            KEY_FILE: $KEY_FILE
            PROJECT: $PROJECT_NAME
            DEPLOYABLES: 'staging.yaml'
            SALT_ROUNDS: $SALT_ROUND
            BACKEND_URL: $BACKEND_URL
            FRONTEND_URL: $FRONTEND_URL
            MAILGUN_DOMAIN: $MAILGUN_DOMAIN
            MAILGUN_API_KEY: $MAILGUN_API_KEY
            TYPEORM_CONNECTION: 'postgres'
            TYPEORM_HOST: $TYPEORM_HOST
            TYPEORM_DATABASE: $TYPEORM_DATABASE
            TYPEORM_USERNAME: $TYPEORM_USERNAME
            TYPEORM_PASSWORD: $TYPEORM_PASSWORD
            TYPEORM_PORT: 29966
            TYPEORM_SYNCHRONIZE: "false"
            TYPEORM_LOGGING: "true"
            TYPEORM_ENTITIES: 'build/entity/*.js'
            TYPEORM_MIGRATIONS: 'build/migrations/*.js'
            TYPEORM_ENTITIES_DIR: 'build/entity'
            TYPEORM_MIGRATIONS_DIR: 'build/migrations'
            TYPEORM_DRIVER_EXTRA: '{ "ssl": true }'

definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        DATABASE_URL: $DATABASE_URL